{
  "name": "SemanticModel",
  "compatibilityLevel": 1550,
  "model": {
    "culture": "fr-FR",
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "sourceQueryCulture": "fr-FR",
    "tables": [
      {
        "name": "dim_calendrier",
        "lineageTag": "1fc76740-6081-40c9-a687-240e24b247d0",
        "columns": [
          {
            "name": "Date",
            "lineageTag": "5fc50ad0-e44c-4339-810a-2fe5f29940df",
            "dataType": "dateTime",
            "sourceColumn": "Date",
            "summarizeBy": "none",
            "formatString": "General Date"
          },
          {
            "name": "Annee",
            "lineageTag": "94e6eff8-896d-4134-ac68-7dfb3fb359e2",
            "dataType": "int64",
            "sourceColumn": "Annee",
            "summarizeBy": "sum"
          },
          {
            "name": "Trimestre",
            "lineageTag": "0338bd2c-3b71-44c9-a754-0587d7572efb",
            "dataType": "int64",
            "sourceColumn": "Trimestre",
            "summarizeBy": "sum"
          },
          {
            "name": "Mois",
            "lineageTag": "de71fcd8-9df5-4cde-9628-ea45b79c08c5",
            "dataType": "int64",
            "sourceColumn": "Mois",
            "summarizeBy": "sum"
          },
          {
            "name": "NomMois",
            "lineageTag": "d58f8f9c-aae9-48ea-a2ef-e6c6a8deb712",
            "dataType": "string",
            "sourceColumn": "NomMois",
            "summarizeBy": "none"
          },
          {
            "name": "Semaine",
            "lineageTag": "71f2113e-6fbd-4548-97ff-8f647076742e",
            "dataType": "int64",
            "sourceColumn": "Semaine",
            "summarizeBy": "sum"
          },
          {
            "name": "JourSemaine",
            "lineageTag": "7352ccc6-a782-4915-9e00-8277e361bb00",
            "dataType": "int64",
            "sourceColumn": "JourSemaine",
            "summarizeBy": "sum"
          },
          {
            "name": "NomJour",
            "lineageTag": "121e932f-1b68-4254-8b85-bf7b6abf7278",
            "dataType": "string",
            "sourceColumn": "NomJour",
            "summarizeBy": "none"
          },
          {
            "name": "EstWeekend",
            "lineageTag": "8765349a-d788-4917-a72f-26fa5ac5d07b",
            "dataType": "int64",
            "sourceColumn": "EstWeekend",
            "summarizeBy": "sum"
          },
          {
            "name": "EstJourFerie",
            "lineageTag": "43b56402-fb0b-4cde-b989-ac6baf63c399",
            "dataType": "int64",
            "sourceColumn": "EstJourFerie",
            "summarizeBy": "sum"
          },
          {
            "name": "Semestre",
            "lineageTag": "1a8a2f57-2caf-483d-a55a-2a15a310075b",
            "dataType": "int64",
            "sourceColumn": "Semestre",
            "summarizeBy": "sum"
          },
          {
            "name": "AnneeMois",
            "lineageTag": "9221a5bc-f2e0-450b-a1a6-c0baa73721b4",
            "dataType": "string",
            "sourceColumn": "AnneeMois",
            "summarizeBy": "none"
          },
          {
            "name": "AnneeTrimestreTxt",
            "lineageTag": "4d68efcf-be6f-45a7-a65e-5881c00b699e",
            "dataType": "string",
            "sourceColumn": "AnneeTrimestreTxt",
            "summarizeBy": "none"
          },
          {
            "type": "calculated",
            "name": "Annee-Mois",
            "lineageTag": "3134c6e8-7a15-493b-956e-7adcf23c917c",
            "dataType": "string",
            "expression": "dim_calendrier[AnneeMois]",
            "summarizeBy": "none"
          },
          {
            "type": "calculated",
            "name": "Annee-Trimestre",
            "lineageTag": "ba0d275f-97b0-40ce-84a6-48982818a592",
            "dataType": "string",
            "expression": "dim_calendrier[AnneeTrimestreTxt]",
            "summarizeBy": "none"
          }
        ],
        "measures": [],
        "partitions": [
          {
            "name": "Partition",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:/Users/AlexandreLARRY/Desktop/Migration Qlik PBI/REPORTIMUS-QLIK-TO-POWERBI/examples/edr-demo/input/dim_calendrier.csv\"),[Delimiter=\",\", Columns=13, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Types\" = Table.TransformColumnTypes(#\"Promoted Headers\", {{\"Date\", type datetime}, {\"Annee\", type number}, {\"Trimestre\", type number}, {\"Mois\", type number}, {\"Semaine\", type number}, {\"JourSemaine\", type number}, {\"EstWeekend\", type number}, {\"EstJourFerie\", type number}, {\"Semestre\", type number}}, \"en-US\")",
                "in",
                "    #\"Changed Types\""
              ]
            }
          }
        ]
      },
      {
        "name": "dim_clients",
        "lineageTag": "9957109f-90cb-47c6-9705-854b443869de",
        "columns": [
          {
            "name": "ClientID",
            "lineageTag": "6e29aa0c-ea11-4828-8b49-15dbfd450b39",
            "dataType": "string",
            "sourceColumn": "ClientID",
            "summarizeBy": "none"
          },
          {
            "name": "Nom",
            "lineageTag": "e506fc05-341b-4927-a404-ce312a9b80a5",
            "dataType": "string",
            "sourceColumn": "Nom",
            "summarizeBy": "none"
          },
          {
            "name": "Prenom",
            "lineageTag": "ed2aed11-6f29-46cb-be06-666c551ccf1c",
            "dataType": "string",
            "sourceColumn": "Prenom",
            "summarizeBy": "none"
          },
          {
            "name": "Email",
            "lineageTag": "7ff22aba-b20b-49df-8eba-b5badc60281a",
            "dataType": "string",
            "sourceColumn": "Email",
            "summarizeBy": "none"
          },
          {
            "name": "Telephone",
            "lineageTag": "18430b5b-2e53-4ccd-a9ad-133ae1a2f112",
            "dataType": "int64",
            "sourceColumn": "Telephone",
            "summarizeBy": "sum"
          },
          {
            "name": "DateNaissance",
            "lineageTag": "afd3b58d-0493-4c56-9e78-84ae2ddce359",
            "dataType": "dateTime",
            "sourceColumn": "DateNaissance",
            "summarizeBy": "none",
            "formatString": "General Date"
          },
          {
            "name": "Segment",
            "lineageTag": "fc010433-0f72-4ca2-a760-97715f64f854",
            "dataType": "string",
            "sourceColumn": "Segment",
            "summarizeBy": "none"
          },
          {
            "name": "Pays",
            "lineageTag": "437145f7-0cd9-49c3-b661-a861b0ccc6e1",
            "dataType": "string",
            "sourceColumn": "Pays",
            "summarizeBy": "none"
          },
          {
            "name": "Ville",
            "lineageTag": "825a2d50-6cf9-4811-88f9-a820302497cb",
            "dataType": "string",
            "sourceColumn": "Ville",
            "summarizeBy": "none"
          },
          {
            "name": "DateEntreeRelation",
            "lineageTag": "cfa5860d-2424-4fa5-9272-e5628dc2cd12",
            "dataType": "dateTime",
            "sourceColumn": "DateEntreeRelation",
            "summarizeBy": "none",
            "formatString": "General Date"
          },
          {
            "name": "Conseiller",
            "lineageTag": "efd892d8-5327-456e-9197-7371cf374c74",
            "dataType": "string",
            "sourceColumn": "Conseiller",
            "summarizeBy": "none"
          },
          {
            "name": "ProfilRisque",
            "lineageTag": "4084fda2-f425-4441-b1a1-6ba31d80abd8",
            "dataType": "string",
            "sourceColumn": "ProfilRisque",
            "summarizeBy": "none"
          },
          {
            "name": "StatutKYC",
            "lineageTag": "c461c81e-7369-4b19-a047-ca6039ea4c67",
            "dataType": "string",
            "sourceColumn": "StatutKYC",
            "summarizeBy": "none"
          },
          {
            "type": "calculated",
            "name": "Nom Complet Client",
            "lineageTag": "fb3051eb-2157-4bac-9f27-747e1608d558",
            "dataType": "string",
            "expression": "dim_clients[Prenom] & \" \" & dim_clients[Nom]",
            "summarizeBy": "none"
          },
          {
            "type": "calculated",
            "name": "Segment Client",
            "lineageTag": "a2f25092-5f80-4eb2-b638-56214ec5826f",
            "dataType": "string",
            "expression": "dim_clients[Segment]",
            "summarizeBy": "none"
          },
          {
            "type": "calculated",
            "name": "Pays Client",
            "lineageTag": "5a78204c-b37c-406c-bbf5-29c61765b742",
            "dataType": "string",
            "expression": "dim_clients[Pays]",
            "summarizeBy": "none"
          },
          {
            "type": "calculated",
            "name": "Anciennete (ans)",
            "lineageTag": "d9ee5eab-c84f-4707-88cf-18214d35897e",
            "dataType": "int64",
            "expression": "DATEDIFF(dim_clients[DateEntreeRelation], TODAY(), YEAR)",
            "summarizeBy": "none"
          },
          {
            "type": "calculated",
            "name": "Nom Complet Conseiller",
            "lineageTag": "ca81a71e-4284-4ced-976f-d9c630c79cb5",
            "dataType": "string",
            "expression": "dim_clients[Conseiller]",
            "summarizeBy": "none"
          }
        ],
        "measures": [
          {
            "name": "Nb Clients",
            "expression": "DISTINCTCOUNT(dim_clients[ClientID])",
            "lineageTag": "f70819ca-050d-4cf3-91ef-10ee39fd4adc"
          },
          {
            "name": "Anciennete Moy. (ans)",
            "expression": "AVERAGE(dim_clients[Anciennete (ans)])",
            "lineageTag": "b6b16d21-d20e-4eda-8ca0-1e1ed1bdd362"
          },
          {
            "name": "Count Distinct ClientID",
            "expression": "DISTINCTCOUNT(dim_clients[ClientID])",
            "lineageTag": "f95924a3-32ef-4898-8d11-7af5c752040a"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:/Users/AlexandreLARRY/Desktop/Migration Qlik PBI/REPORTIMUS-QLIK-TO-POWERBI/examples/edr-demo/input/dim_clients.csv\"),[Delimiter=\",\", Columns=13, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Types\" = Table.TransformColumnTypes(#\"Promoted Headers\", {{\"Telephone\", type number}, {\"DateNaissance\", type datetime}, {\"DateEntreeRelation\", type datetime}}, \"en-US\")",
                "in",
                "    #\"Changed Types\""
              ]
            }
          }
        ]
      },
      {
        "name": "dim_conseillers",
        "lineageTag": "14789b9e-9b26-426b-8298-c87b7fb94ed1",
        "columns": [
          {
            "name": "ConseillerID",
            "lineageTag": "125deeef-1ac5-4673-9543-a0d90dfe4873",
            "dataType": "string",
            "sourceColumn": "ConseillerID",
            "summarizeBy": "none"
          },
          {
            "name": "Nom",
            "lineageTag": "e6fbcf5f-11a5-4902-8342-645bdc281211",
            "dataType": "string",
            "sourceColumn": "Nom",
            "summarizeBy": "none"
          },
          {
            "name": "Prenom",
            "lineageTag": "99172945-769a-4cf2-8830-988f09315dae",
            "dataType": "string",
            "sourceColumn": "Prenom",
            "summarizeBy": "none"
          },
          {
            "name": "Email",
            "lineageTag": "00593a68-1fd8-4645-8a84-9e0ad9d270da",
            "dataType": "string",
            "sourceColumn": "Email",
            "summarizeBy": "none"
          },
          {
            "name": "Bureau",
            "lineageTag": "643783e9-3eeb-494e-acdd-375a6e816a70",
            "dataType": "string",
            "sourceColumn": "Bureau",
            "summarizeBy": "none"
          },
          {
            "name": "Equipe",
            "lineageTag": "e684bc44-77a2-478f-b8f2-4ee756d96e55",
            "dataType": "string",
            "sourceColumn": "Equipe",
            "summarizeBy": "none"
          },
          {
            "name": "AnneeExperience",
            "lineageTag": "1b232d8a-3def-44fd-aa0d-a52a55122139",
            "dataType": "int64",
            "sourceColumn": "AnneeExperience",
            "summarizeBy": "sum"
          },
          {
            "name": "Certification",
            "lineageTag": "f9c420b1-441f-49da-8f2d-7671c543038e",
            "dataType": "string",
            "sourceColumn": "Certification",
            "summarizeBy": "none"
          },
          {
            "name": "NbClients",
            "lineageTag": "ebd81f52-aac1-4cb2-a858-155978a36de0",
            "dataType": "int64",
            "sourceColumn": "NbClients",
            "summarizeBy": "sum"
          },
          {
            "name": "AuM_EUR",
            "lineageTag": "6f9289f6-0567-4a11-85b7-1a24bace955b",
            "dataType": "double",
            "sourceColumn": "AuM_EUR",
            "summarizeBy": "sum"
          }
        ],
        "measures": [],
        "partitions": [
          {
            "name": "Partition",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:/Users/AlexandreLARRY/Desktop/Migration Qlik PBI/REPORTIMUS-QLIK-TO-POWERBI/examples/edr-demo/input/dim_conseillers.csv\"),[Delimiter=\",\", Columns=10, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Types\" = Table.TransformColumnTypes(#\"Promoted Headers\", {{\"AnneeExperience\", type number}, {\"NbClients\", type number}, {\"AuM_EUR\", type number}}, \"en-US\")",
                "in",
                "    #\"Changed Types\""
              ]
            }
          }
        ]
      },
      {
        "name": "dim_instruments",
        "lineageTag": "fd123dc3-800b-48bf-92ff-7dc434c72012",
        "columns": [
          {
            "name": "InstrumentID",
            "lineageTag": "885ac5bc-6aea-4fd7-a9dd-6a1aca5ec43c",
            "dataType": "string",
            "sourceColumn": "InstrumentID",
            "summarizeBy": "none"
          },
          {
            "name": "NomInstrument",
            "lineageTag": "0737daef-2b94-412f-b789-7fe1fa8791b9",
            "dataType": "string",
            "sourceColumn": "NomInstrument",
            "summarizeBy": "none"
          },
          {
            "name": "TypeInstrument",
            "lineageTag": "0d06adfb-3ae6-47d7-a9bd-f9e3d2482154",
            "dataType": "string",
            "sourceColumn": "TypeInstrument",
            "summarizeBy": "none"
          },
          {
            "name": "Classe Actif",
            "lineageTag": "2c3ff956-d452-4c0b-9f68-14fbd11765c7",
            "dataType": "string",
            "sourceColumn": "Classe Actif",
            "summarizeBy": "none"
          },
          {
            "name": "Devise",
            "lineageTag": "a05d2257-a918-4ec0-af89-4c0864567d60",
            "dataType": "string",
            "sourceColumn": "Devise",
            "summarizeBy": "none"
          },
          {
            "name": "Pays",
            "lineageTag": "6fa00e88-61a4-4c12-9c72-e5e194ea6d98",
            "dataType": "string",
            "sourceColumn": "Pays",
            "summarizeBy": "none"
          },
          {
            "name": "ISIN",
            "lineageTag": "44d37727-07e1-4f17-ab96-228fc9c36939",
            "dataType": "string",
            "sourceColumn": "ISIN",
            "summarizeBy": "none"
          },
          {
            "name": "Emetteur",
            "lineageTag": "fdce5faf-b7c0-4ca6-8224-00ffd2e22489",
            "dataType": "string",
            "sourceColumn": "Emetteur",
            "summarizeBy": "none"
          },
          {
            "name": "NiveauRisque",
            "lineageTag": "9af278b5-e39c-4c99-a878-14c526b8052c",
            "dataType": "string",
            "sourceColumn": "NiveauRisque",
            "summarizeBy": "none"
          },
          {
            "name": "FraisGestion_pct",
            "lineageTag": "6b4ca87b-09d3-4e4d-a3d9-9d779f23a321",
            "dataType": "double",
            "sourceColumn": "FraisGestion_pct",
            "summarizeBy": "sum"
          },
          {
            "type": "calculated",
            "name": "Macro Classe Actif",
            "lineageTag": "13c6a318-bd53-4465-8eab-c33f83099dcb",
            "dataType": "string",
            "expression": "dim_instruments[Macro Classe Actif]",
            "summarizeBy": "none"
          }
        ],
        "measures": [
          {
            "name": "Count InstrumentID",
            "expression": "DISTINCTCOUNT(dim_instruments[InstrumentID])",
            "lineageTag": "1126f8a1-8331-46c0-a6ee-35578b615e5b"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:/Users/AlexandreLARRY/Desktop/Migration Qlik PBI/REPORTIMUS-QLIK-TO-POWERBI/examples/edr-demo/input/dim_instruments.csv\"),[Delimiter=\",\", Columns=10, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Types\" = Table.TransformColumnTypes(#\"Promoted Headers\", {{\"FraisGestion_pct\", type number}}, \"en-US\")",
                "in",
                "    #\"Changed Types\""
              ]
            }
          }
        ]
      },
      {
        "name": "dim_portefeuilles",
        "lineageTag": "21ef2eb2-7f50-4d89-ac25-3e7929f8cbb2",
        "columns": [
          {
            "name": "PortefeuilleID",
            "lineageTag": "33266ac0-e538-4585-9033-396eefc2e127",
            "dataType": "string",
            "sourceColumn": "PortefeuilleID",
            "summarizeBy": "none"
          },
          {
            "name": "ClientID",
            "lineageTag": "19b5cfb1-9af2-4a21-a73b-c259f7998aae",
            "dataType": "string",
            "sourceColumn": "ClientID",
            "summarizeBy": "none"
          },
          {
            "name": "TypePortefeuille",
            "lineageTag": "5c3d09a0-053f-4d64-9cf7-f73a993e2103",
            "dataType": "string",
            "sourceColumn": "TypePortefeuille",
            "summarizeBy": "none"
          },
          {
            "name": "DateOuverture",
            "lineageTag": "0ba0a6a8-7565-46d1-a416-ea0634383352",
            "dataType": "dateTime",
            "sourceColumn": "DateOuverture",
            "summarizeBy": "none",
            "formatString": "General Date"
          },
          {
            "name": "Devise",
            "lineageTag": "e8b69051-e77a-4430-9f3f-bba875c9e37c",
            "dataType": "string",
            "sourceColumn": "Devise",
            "summarizeBy": "none"
          },
          {
            "name": "Statut",
            "lineageTag": "715768f6-e0d5-4372-8f55-ee55be3c5c7c",
            "dataType": "string",
            "sourceColumn": "Statut",
            "summarizeBy": "none"
          },
          {
            "name": "ObjectifInvestissement",
            "lineageTag": "70e8c9c1-b4fa-4b8a-a940-008b69250538",
            "dataType": "string",
            "sourceColumn": "ObjectifInvestissement",
            "summarizeBy": "none"
          },
          {
            "name": "HorizonInvestissement",
            "lineageTag": "42cb77fb-8107-498f-b87e-fc839ac050d9",
            "dataType": "string",
            "sourceColumn": "HorizonInvestissement",
            "summarizeBy": "none"
          },
          {
            "name": "BenchmarkRef",
            "lineageTag": "44988ea6-177f-4e61-aed2-effdea027f8e",
            "dataType": "string",
            "sourceColumn": "BenchmarkRef",
            "summarizeBy": "none"
          },
          {
            "type": "calculated",
            "name": "Type Portefeuille",
            "lineageTag": "b08f0295-55f4-4d2b-9956-a95358fb0c64",
            "dataType": "string",
            "expression": "dim_portefeuilles[TypePortefeuille]",
            "summarizeBy": "none"
          }
        ],
        "measures": [
          {
            "name": "Nb Portef. Moy. / Client",
            "expression": "DISTINCTCOUNT(dim_portefeuilles[PortefeuilleID]) / DISTINCTCOUNT(dim_clients[ClientID])",
            "lineageTag": "fd01227b-df0f-4d37-a37f-72b0a693089e"
          },
          {
            "name": "Nb Portefeuilles",
            "expression": "DISTINCTCOUNT(dim_portefeuilles[PortefeuilleID])",
            "lineageTag": "45f84c13-2e45-4a9c-b2cb-026921a20613"
          },
          {
            "name": "Count PortefeuilleID",
            "expression": "COUNT(dim_portefeuilles[PortefeuilleID])",
            "lineageTag": "6a6fdce5-1b8c-466c-9dea-9182dab35cc3"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:/Users/AlexandreLARRY/Desktop/Migration Qlik PBI/REPORTIMUS-QLIK-TO-POWERBI/examples/edr-demo/input/dim_portefeuilles.csv\"),[Delimiter=\",\", Columns=9, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Types\" = Table.TransformColumnTypes(#\"Promoted Headers\", {{\"DateOuverture\", type datetime}}, \"en-US\")",
                "in",
                "    #\"Changed Types\""
              ]
            }
          }
        ]
      },
      {
        "name": "fact_alertes_risque",
        "lineageTag": "0b02d2b5-eceb-42eb-93c7-4c212e81e130",
        "columns": [
          {
            "name": "AlerteID",
            "lineageTag": "34c0a997-a2ef-44c7-8011-6d7ea1d1c63f",
            "dataType": "string",
            "sourceColumn": "AlerteID",
            "summarizeBy": "none"
          },
          {
            "name": "PortefeuilleID",
            "lineageTag": "16cd795b-2d40-483a-9fc2-7cc65da4e083",
            "dataType": "string",
            "sourceColumn": "PortefeuilleID",
            "summarizeBy": "none"
          },
          {
            "name": "ClientID",
            "lineageTag": "57d97a4d-a721-4560-9588-41b7ee4818e2",
            "dataType": "string",
            "sourceColumn": "ClientID",
            "summarizeBy": "none"
          },
          {
            "name": "DateAlerte",
            "lineageTag": "463bcf27-de3a-4acb-b6c4-face7a62fdd6",
            "dataType": "dateTime",
            "sourceColumn": "DateAlerte",
            "summarizeBy": "none",
            "formatString": "General Date"
          },
          {
            "name": "TypeAlerte",
            "lineageTag": "04e65037-770c-4912-a84a-eccc655da394",
            "dataType": "string",
            "sourceColumn": "TypeAlerte",
            "summarizeBy": "none"
          },
          {
            "name": "Severite",
            "lineageTag": "2e20cc16-c3c2-4ef9-ad8c-ed2b8378f54e",
            "dataType": "string",
            "sourceColumn": "Severite",
            "summarizeBy": "none"
          },
          {
            "name": "Statut",
            "lineageTag": "b8e1d924-6d12-42d5-9a28-406227a9e7f3",
            "dataType": "string",
            "sourceColumn": "Statut",
            "summarizeBy": "none"
          },
          {
            "name": "Description",
            "lineageTag": "f2eafebd-d58a-4c60-a265-8769a05805ed",
            "dataType": "string",
            "sourceColumn": "Description",
            "summarizeBy": "none"
          },
          {
            "name": "ValeurMesure",
            "lineageTag": "cdf52b9d-967a-495d-8aaf-613c91748274",
            "dataType": "double",
            "sourceColumn": "ValeurMesure",
            "summarizeBy": "sum"
          },
          {
            "name": "SeuilAlerte",
            "lineageTag": "408b2441-16fe-429f-82d2-e2b15a211935",
            "dataType": "double",
            "sourceColumn": "SeuilAlerte",
            "summarizeBy": "sum"
          },
          {
            "name": "DateResolution",
            "lineageTag": "2d703c71-f1d7-40e8-b537-3d9e54c885fc",
            "dataType": "dateTime",
            "sourceColumn": "DateResolution",
            "summarizeBy": "none",
            "formatString": "General Date"
          },
          {
            "type": "calculated",
            "name": "Type Alerte",
            "lineageTag": "5a86616b-d9ca-46c5-bc07-f1bf2263758a",
            "dataType": "string",
            "expression": "fact_alertes_risque[TypeAlerte]",
            "summarizeBy": "none"
          },
          {
            "type": "calculated",
            "name": "Statut Alerte",
            "lineageTag": "ccf53446-7991-4c00-a6a3-57c5d42d4796",
            "dataType": "string",
            "expression": "fact_alertes_risque[Statut]",
            "summarizeBy": "none"
          }
        ],
        "measures": [
          {
            "name": "Count AlerteID",
            "expression": "COUNT(fact_alertes_risque[AlerteID])",
            "lineageTag": "48c7dc06-3857-4cdf-906c-cda640db5824"
          },
          {
            "name": "Count Critique AlerteID",
            "expression": "CALCULATE(COUNT(fact_alertes_risque[AlerteID]), fact_alertes_risque[Severite] = \"Critique\")",
            "lineageTag": "dfc1bdf6-ad4e-4134-ac5c-7f2b4d88e507"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:/Users/AlexandreLARRY/Desktop/Migration Qlik PBI/REPORTIMUS-QLIK-TO-POWERBI/examples/edr-demo/input/fact_alertes_risque.csv\"),[Delimiter=\",\", Columns=11, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Types\" = Table.TransformColumnTypes(#\"Promoted Headers\", {{\"DateAlerte\", type datetime}, {\"ValeurMesure\", type number}, {\"SeuilAlerte\", type number}, {\"DateResolution\", type datetime}}, \"en-US\")",
                "in",
                "    #\"Changed Types\""
              ]
            }
          }
        ]
      },
      {
        "name": "fact_cours_historiques",
        "lineageTag": "cf6c7f25-8f18-484a-be73-4f30286bbd6d",
        "columns": [
          {
            "name": "Date",
            "lineageTag": "1a05a274-5fcd-4a42-8939-d377981bae7b",
            "dataType": "dateTime",
            "sourceColumn": "Date",
            "summarizeBy": "none",
            "formatString": "General Date"
          },
          {
            "name": "InstrumentID",
            "lineageTag": "f303df90-25d5-4172-bbe8-03f64800e8e6",
            "dataType": "string",
            "sourceColumn": "InstrumentID",
            "summarizeBy": "none"
          },
          {
            "name": "PrixOuverture",
            "lineageTag": "3ff95e91-ab41-4d31-98d2-de65372d4d6f",
            "dataType": "double",
            "sourceColumn": "PrixOuverture",
            "summarizeBy": "sum"
          },
          {
            "name": "PrixHaut",
            "lineageTag": "caa1b630-61dc-42d7-a463-87e9362d7c31",
            "dataType": "double",
            "sourceColumn": "PrixHaut",
            "summarizeBy": "sum"
          },
          {
            "name": "PrixBas",
            "lineageTag": "230a2fef-ac21-42fe-a290-97ebd0b63dba",
            "dataType": "double",
            "sourceColumn": "PrixBas",
            "summarizeBy": "sum"
          },
          {
            "name": "PrixCloture",
            "lineageTag": "56534157-adc3-4192-a47d-3060e3aa2690",
            "dataType": "double",
            "sourceColumn": "PrixCloture",
            "summarizeBy": "sum"
          },
          {
            "name": "Volume",
            "lineageTag": "462e4cdd-147b-4087-80b1-48a4876f082b",
            "dataType": "double",
            "sourceColumn": "Volume",
            "summarizeBy": "sum"
          },
          {
            "name": "Devise",
            "lineageTag": "8656ef9a-b8c8-4cd7-871c-a2d7362cecc2",
            "dataType": "string",
            "sourceColumn": "Devise",
            "summarizeBy": "none"
          }
        ],
        "measures": [
          {
            "name": "Sum Volume",
            "expression": "SUM(fact_cours_historiques[Volume])",
            "lineageTag": "27c253d1-e69a-467f-a2bc-d8e1e537dd1c"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:/Users/AlexandreLARRY/Desktop/Migration Qlik PBI/REPORTIMUS-QLIK-TO-POWERBI/examples/edr-demo/input/fact_cours_historiques.csv\"),[Delimiter=\",\", Columns=8, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Types\" = Table.TransformColumnTypes(#\"Promoted Headers\", {{\"Date\", type datetime}, {\"PrixOuverture\", type number}, {\"PrixHaut\", type number}, {\"PrixBas\", type number}, {\"PrixCloture\", type number}, {\"Volume\", type number}}, \"en-US\")",
                "in",
                "    #\"Changed Types\""
              ]
            }
          }
        ]
      },
      {
        "name": "fact_performances",
        "lineageTag": "8bf2751e-1b83-4714-84cf-385b21525f79",
        "columns": [
          {
            "name": "PeriodeDate",
            "lineageTag": "122e06c9-8213-4f6b-8ab7-e2c6b432bf10",
            "dataType": "dateTime",
            "sourceColumn": "PeriodeDate",
            "summarizeBy": "none",
            "formatString": "General Date"
          },
          {
            "name": "PortefeuilleID",
            "lineageTag": "88c6ce6d-080e-453b-ad48-cda4addaa5f5",
            "dataType": "string",
            "sourceColumn": "PortefeuilleID",
            "summarizeBy": "none"
          },
          {
            "name": "Rendement_pct",
            "lineageTag": "bd087582-574d-4862-b1e5-a778803c102d",
            "dataType": "double",
            "sourceColumn": "Rendement_pct",
            "summarizeBy": "sum"
          },
          {
            "name": "Benchmark_pct",
            "lineageTag": "30d8f44e-ab33-4017-afa9-f0776bf56c88",
            "dataType": "double",
            "sourceColumn": "Benchmark_pct",
            "summarizeBy": "sum"
          },
          {
            "name": "Alpha_pct",
            "lineageTag": "4063765b-dc31-4f33-a28b-1a71c53fa25e",
            "dataType": "double",
            "sourceColumn": "Alpha_pct",
            "summarizeBy": "sum"
          },
          {
            "name": "Volatilite_pct",
            "lineageTag": "41180ea7-d05e-4c2b-9a5b-a9fd0b6199d2",
            "dataType": "double",
            "sourceColumn": "Volatilite_pct",
            "summarizeBy": "sum"
          },
          {
            "name": "RatioSharpe",
            "lineageTag": "523d9bba-3bb3-4728-8d50-ec85b6ea01ec",
            "dataType": "double",
            "sourceColumn": "RatioSharpe",
            "summarizeBy": "sum"
          },
          {
            "name": "MaxDrawdown_pct",
            "lineageTag": "c82f4966-ce34-4271-9f65-b4e8836bd926",
            "dataType": "double",
            "sourceColumn": "MaxDrawdown_pct",
            "summarizeBy": "sum"
          },
          {
            "name": "ValeurPortefeuille_EUR",
            "lineageTag": "ee3bd7a8-63ab-4447-b6b7-5e9b921494fa",
            "dataType": "double",
            "sourceColumn": "ValeurPortefeuille_EUR",
            "summarizeBy": "sum"
          },
          {
            "name": "FluxNets_EUR",
            "lineageTag": "cdff68cd-c93c-4278-bc27-f7534fb4e489",
            "dataType": "double",
            "sourceColumn": "FluxNets_EUR",
            "summarizeBy": "sum"
          },
          {
            "name": "RendementCumule_pct",
            "lineageTag": "0d618373-1396-4630-903e-91d28b221118",
            "dataType": "double",
            "sourceColumn": "RendementCumule_pct",
            "summarizeBy": "sum"
          },
          {
            "type": "calculated",
            "name": "Rendement (%)",
            "lineageTag": "eafdd4f3-bf9a-429a-9b59-7f635a64a11b",
            "dataType": "double",
            "expression": "fact_performances[Rendement_pct]",
            "summarizeBy": "none"
          },
          {
            "type": "calculated",
            "name": "Benchmark (%)",
            "lineageTag": "a05a7e13-8c7f-49d5-ac0b-1cf88745d29f",
            "dataType": "double",
            "expression": "fact_performances[Benchmark_pct]",
            "summarizeBy": "none"
          },
          {
            "type": "calculated",
            "name": "Alpha (%)",
            "lineageTag": "a575bf0d-e3ab-4540-a1c4-cd7a99db134b",
            "dataType": "double",
            "expression": "fact_performances[Alpha_pct]",
            "summarizeBy": "none"
          },
          {
            "type": "calculated",
            "name": "Volatilite (%)",
            "lineageTag": "141d3ee0-7d16-45b3-b5a9-8605f69c1967",
            "dataType": "double",
            "expression": "fact_performances[Volatilite_pct]",
            "summarizeBy": "none"
          },
          {
            "type": "calculated",
            "name": "Ratio Sharpe",
            "lineageTag": "2a0fcdee-5548-4f22-b4a0-35b1a1effe4d",
            "dataType": "double",
            "expression": "fact_performances[RatioSharpe]",
            "summarizeBy": "none"
          },
          {
            "type": "calculated",
            "name": "Valeur Portefeuille (EUR)",
            "lineageTag": "b92f23db-e240-488e-ad5c-0c6b9ad094b5",
            "dataType": "double",
            "expression": "fact_performances[ValeurPortefeuille_EUR]",
            "summarizeBy": "none"
          },
          {
            "type": "calculated",
            "name": "Flux Nets (EUR)",
            "lineageTag": "8c88b97f-8f86-444b-87f9-2e222ba53ec2",
            "dataType": "double",
            "expression": "fact_performances[FluxNets_EUR]",
            "summarizeBy": "none"
          },
          {
            "type": "calculated",
            "name": "Rendement Cumule (%)",
            "lineageTag": "85f68530-45f4-4565-a94d-8baa948da023",
            "dataType": "double",
            "expression": "fact_performances[RendementCumule_pct]",
            "summarizeBy": "none"
          },
          {
            "type": "calculated",
            "name": "Vs Benchmark",
            "lineageTag": "c11f8bf2-74a8-4985-9f47-f9e35ef772ba",
            "dataType": "string",
            "expression": "IF(fact_performances[Alpha_pct] >= 0, \"Surperforme\", \"Sous-performe\")",
            "summarizeBy": "none"
          }
        ],
        "measures": [
          {
            "name": "Rendement Moyen (%)",
            "expression": "AVERAGE(fact_performances[Rendement_pct])",
            "lineageTag": "af7a3975-8647-4134-9d5c-9def415df5b4"
          },
          {
            "name": "Benchmark Moyen (%)",
            "expression": "AVERAGE(fact_performances[Benchmark_pct])",
            "lineageTag": "61159379-1cb4-4ec4-8ada-e2154d7df86d"
          },
          {
            "name": "Ratio Sharpe Moyen",
            "expression": "AVERAGE(fact_performances[RatioSharpe])",
            "lineageTag": "02f48907-4112-4cd1-9dc1-6e2e73636e81"
          },
          {
            "name": "Max Drawdown (%)",
            "expression": "MIN(fact_performances[MaxDrawdown_pct])",
            "lineageTag": "13e26d98-2255-42af-8097-f1f67c51a9f1"
          },
          {
            "name": "Sum Flux Nets (EUR)",
            "expression": "SUM(fact_performances[FluxNets_EUR])",
            "lineageTag": "eeb5bb65-e0a0-431b-94c7-ddaf9d1d4b77"
          },
          {
            "name": "Avg Rendement (%)",
            "expression": "AVERAGE(fact_performances[Rendement_pct])",
            "lineageTag": "dd235679-e3bd-47fa-a59e-d37e29ad6267"
          },
          {
            "name": "Avg Benchmark (%)",
            "expression": "AVERAGE(fact_performances[Benchmark_pct])",
            "lineageTag": "c568aa66-336d-4b3c-a556-2c32a6a38646"
          },
          {
            "name": "Avg Alpha (%)",
            "expression": "AVERAGE(fact_performances[Alpha_pct])",
            "lineageTag": "70d1b3a3-94cd-4068-ba7d-a02fda3938dd"
          },
          {
            "name": "Avg Volatilite (%)",
            "expression": "AVERAGE(fact_performances[Volatilite_pct])",
            "lineageTag": "7a3943d2-ea87-4f44-a9ad-79e91eae94a9"
          },
          {
            "name": "Avg Rendement Cumule (%)",
            "expression": "AVERAGE(fact_performances[RendementCumule_pct])",
            "lineageTag": "9037eafd-3077-462a-a187-9c40d032025c"
          },
          {
            "name": "Avg Ratio Sharpe",
            "expression": "AVERAGE(fact_performances[RatioSharpe])",
            "lineageTag": "125f1213-1154-439c-8a53-f2b7de8482a9"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:/Users/AlexandreLARRY/Desktop/Migration Qlik PBI/REPORTIMUS-QLIK-TO-POWERBI/examples/edr-demo/input/fact_performances.csv\"),[Delimiter=\",\", Columns=11, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Types\" = Table.TransformColumnTypes(#\"Promoted Headers\", {{\"PeriodeDate\", type datetime}, {\"Rendement_pct\", type number}, {\"Benchmark_pct\", type number}, {\"Alpha_pct\", type number}, {\"Volatilite_pct\", type number}, {\"RatioSharpe\", type number}, {\"MaxDrawdown_pct\", type number}, {\"ValeurPortefeuille_EUR\", type number}, {\"FluxNets_EUR\", type number}, {\"RendementCumule_pct\", type number}}, \"en-US\")",
                "in",
                "    #\"Changed Types\""
              ]
            }
          }
        ]
      },
      {
        "name": "fact_positions",
        "lineageTag": "81aa40b0-5f88-443a-84ad-7ea5f094b5c9",
        "columns": [
          {
            "name": "SnapshotDate",
            "lineageTag": "79da583c-48a7-4abe-bd09-c1d451519b0e",
            "dataType": "dateTime",
            "sourceColumn": "SnapshotDate",
            "summarizeBy": "none",
            "formatString": "General Date"
          },
          {
            "name": "PortefeuilleID",
            "lineageTag": "dc81311f-0d49-4534-b016-02cb47028a87",
            "dataType": "string",
            "sourceColumn": "PortefeuilleID",
            "summarizeBy": "none"
          },
          {
            "name": "InstrumentID",
            "lineageTag": "f1d9a50f-7900-4444-9ebb-3e520b11281b",
            "dataType": "string",
            "sourceColumn": "InstrumentID",
            "summarizeBy": "none"
          },
          {
            "name": "Quantite",
            "lineageTag": "7cd039a0-ce56-4ac3-af15-a3aedb504645",
            "dataType": "double",
            "sourceColumn": "Quantite",
            "summarizeBy": "sum"
          },
          {
            "name": "PrixRevientUnitaire",
            "lineageTag": "cb96007f-3d5b-4318-a277-c033d1ed3573",
            "dataType": "double",
            "sourceColumn": "PrixRevientUnitaire",
            "summarizeBy": "sum"
          },
          {
            "name": "PrixMarcheUnitaire",
            "lineageTag": "5cd076ea-79c0-4c3f-b72e-c3d7b0f1a392",
            "dataType": "double",
            "sourceColumn": "PrixMarcheUnitaire",
            "summarizeBy": "sum"
          },
          {
            "name": "ValeurAchat_EUR",
            "lineageTag": "0e43525d-8a9d-4455-a82d-369f2cd64e8f",
            "dataType": "double",
            "sourceColumn": "ValeurAchat_EUR",
            "summarizeBy": "sum"
          },
          {
            "name": "ValeurMarche_EUR",
            "lineageTag": "482384b7-b84e-4071-9c07-b81d8bd9d52a",
            "dataType": "double",
            "sourceColumn": "ValeurMarche_EUR",
            "summarizeBy": "sum"
          },
          {
            "name": "PnL_EUR",
            "lineageTag": "7dc5457a-e80a-4075-afdf-8e44ed6554d4",
            "dataType": "double",
            "sourceColumn": "PnL_EUR",
            "summarizeBy": "sum"
          },
          {
            "name": "PnL_pct",
            "lineageTag": "1c2dcb72-43b0-40a1-92dd-865782334397",
            "dataType": "double",
            "sourceColumn": "PnL_pct",
            "summarizeBy": "sum"
          },
          {
            "name": "PoidsPortefeuille_pct",
            "lineageTag": "2c24f2e9-7c35-4d75-9337-466217a28093",
            "dataType": "double",
            "sourceColumn": "PoidsPortefeuille_pct",
            "summarizeBy": "sum"
          },
          {
            "name": "Devise",
            "lineageTag": "ca146e5e-5e66-4fc7-bf13-47eaaa1584a3",
            "dataType": "string",
            "sourceColumn": "Devise",
            "summarizeBy": "none"
          },
          {
            "type": "calculated",
            "name": "Valeur Marche (EUR)",
            "lineageTag": "8941c8db-0486-4831-8ba7-8a240e676a76",
            "dataType": "double",
            "expression": "fact_positions[ValeurMarche_EUR]",
            "summarizeBy": "none"
          },
          {
            "type": "calculated",
            "name": "PnL (EUR)",
            "lineageTag": "6dbbb178-0a50-4944-a40b-626e627b15eb",
            "dataType": "double",
            "expression": "fact_positions[PnL_EUR]",
            "summarizeBy": "none"
          },
          {
            "type": "calculated",
            "name": "Valeur Achat (EUR)",
            "lineageTag": "625ff2b0-9921-4b06-aafc-3b05034eede8",
            "dataType": "double",
            "expression": "fact_positions[ValeurAchat_EUR]",
            "summarizeBy": "none"
          },
          {
            "type": "calculated",
            "name": "PnL (%)",
            "lineageTag": "d2c2f227-30d2-4a93-97b8-9b3739348985",
            "dataType": "double",
            "expression": "fact_positions[PnL_pct]",
            "summarizeBy": "none"
          },
          {
            "type": "calculated",
            "name": "Poids Portefeuille (%)",
            "lineageTag": "a0b03323-7b97-46b8-b3db-bdfa49923487",
            "dataType": "double",
            "expression": "fact_positions[PoidsPortefeuille_pct]",
            "summarizeBy": "none"
          },
          {
            "type": "calculated",
            "name": "Signe PnL",
            "lineageTag": "48e49d67-809f-4452-9ede-baa05fffa0c3",
            "dataType": "string",
            "expression": "IF(fact_positions[PnL_EUR] >= 0, \"Positif\", \"Negatif\")",
            "summarizeBy": "none"
          }
        ],
        "measures": [
          {
            "name": "AuM Moyen / Client (EUR)",
            "expression": "SUM(fact_positions[ValeurMarche_EUR]) / DISTINCTCOUNT(dim_clients[ClientID])",
            "lineageTag": "98cf692c-9d31-446a-919e-086412342346"
          },
          {
            "name": "AuM",
            "expression": "SUM(fact_positions[ValeurMarche_EUR])",
            "lineageTag": "01fed89b-a050-407f-bdde-683c70218ee6"
          },
          {
            "name": "Sum PnL (EUR)",
            "expression": "SUM(fact_positions[PnL_EUR])",
            "lineageTag": "8e248dd1-8986-4edc-8b7b-205c2628f88b"
          },
          {
            "name": "AuM Total (EUR)",
            "expression": "SUM(fact_positions[ValeurMarche_EUR])",
            "lineageTag": "230a3804-0fff-45d1-92ab-809dda8f7c4a"
          },
          {
            "name": "PnL Total (EUR)",
            "expression": "SUM(fact_positions[PnL_EUR])",
            "lineageTag": "2dcbea01-ee84-40e3-8976-fd89a60a5b59"
          },
          {
            "name": "Sum Valeur Marche (EUR)",
            "expression": "SUM(fact_positions[ValeurMarche_EUR])",
            "lineageTag": "fc6e5911-4de8-4bd0-85cc-4f5745881d32"
          },
          {
            "name": "Sum PnL (%)",
            "expression": "SUM(fact_positions[PnL_pct])",
            "lineageTag": "bb54468c-ce63-4b1a-906f-886675b20f7b"
          },
          {
            "name": "Avg PnL (%)",
            "expression": "AVERAGE(fact_positions[PnL_pct])",
            "lineageTag": "544cbab4-4ced-4be9-be8f-17e61c946ea5"
          },
          {
            "name": "Sum Valeur Achat (EUR)",
            "expression": "SUM(fact_positions[ValeurAchat_EUR])",
            "lineageTag": "018e4258-4d3c-4fe4-ba08-3cfda2c17e18"
          },
          {
            "name": "Avg Poids Portefeuille (%)",
            "expression": "AVERAGE(fact_positions[PoidsPortefeuille_pct])",
            "lineageTag": "3cea7a9f-732c-4446-a534-753e7d220244"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:/Users/AlexandreLARRY/Desktop/Migration Qlik PBI/REPORTIMUS-QLIK-TO-POWERBI/examples/edr-demo/input/fact_positions.csv\"),[Delimiter=\",\", Columns=12, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Types\" = Table.TransformColumnTypes(#\"Promoted Headers\", {{\"SnapshotDate\", type datetime}, {\"Quantite\", type number}, {\"PrixRevientUnitaire\", type number}, {\"PrixMarcheUnitaire\", type number}, {\"ValeurAchat_EUR\", type number}, {\"ValeurMarche_EUR\", type number}, {\"PnL_EUR\", type number}, {\"PnL_pct\", type number}, {\"PoidsPortefeuille_pct\", type number}}, \"en-US\")",
                "in",
                "    #\"Changed Types\""
              ]
            }
          }
        ]
      },
      {
        "name": "fact_transactions",
        "lineageTag": "dc4b43e5-9bbc-414c-99a9-b9e3a67eefd9",
        "columns": [
          {
            "name": "TransactionID",
            "lineageTag": "d083db1b-283a-4a85-8441-de2f2dba75b6",
            "dataType": "string",
            "sourceColumn": "TransactionID",
            "summarizeBy": "none"
          },
          {
            "name": "PortefeuilleID",
            "lineageTag": "c660d0b8-9fcc-4d11-bbca-8eefb3786603",
            "dataType": "string",
            "sourceColumn": "PortefeuilleID",
            "summarizeBy": "none"
          },
          {
            "name": "InstrumentID",
            "lineageTag": "38578ee3-f8d9-439e-8180-6f397c3c57c1",
            "dataType": "string",
            "sourceColumn": "InstrumentID",
            "summarizeBy": "none"
          },
          {
            "name": "DateTransaction",
            "lineageTag": "763378c9-0dac-4eb0-9955-e5af6974e884",
            "dataType": "dateTime",
            "sourceColumn": "DateTransaction",
            "summarizeBy": "none",
            "formatString": "General Date"
          },
          {
            "name": "TypeTransaction",
            "lineageTag": "cae53487-ffd5-4c5a-a94d-9f7ffd5c695e",
            "dataType": "string",
            "sourceColumn": "TypeTransaction",
            "summarizeBy": "none"
          },
          {
            "name": "Quantite",
            "lineageTag": "dadcf837-fbc8-4890-83bf-544d42892bb3",
            "dataType": "double",
            "sourceColumn": "Quantite",
            "summarizeBy": "sum"
          },
          {
            "name": "PrixUnitaire",
            "lineageTag": "b985f893-657d-4eb4-9598-60fe7360b559",
            "dataType": "double",
            "sourceColumn": "PrixUnitaire",
            "summarizeBy": "sum"
          },
          {
            "name": "MontantBrut",
            "lineageTag": "21bf1ec5-2441-4190-9616-13ed4445b13f",
            "dataType": "double",
            "sourceColumn": "MontantBrut",
            "summarizeBy": "sum"
          },
          {
            "name": "Frais",
            "lineageTag": "93f6cee3-c723-427d-997f-96ceccd2d90a",
            "dataType": "double",
            "sourceColumn": "Frais",
            "summarizeBy": "sum"
          },
          {
            "name": "MontantNet",
            "lineageTag": "16908b7b-d4d0-412b-939c-abd9abce2e03",
            "dataType": "double",
            "sourceColumn": "MontantNet",
            "summarizeBy": "sum"
          },
          {
            "name": "Devise",
            "lineageTag": "f5f9b323-77a5-4b39-a2da-d026291f330a",
            "dataType": "string",
            "sourceColumn": "Devise",
            "summarizeBy": "none"
          },
          {
            "name": "TauxChange_EUR",
            "lineageTag": "ccf90cc6-9c3f-43af-bd0c-39e2844dd26a",
            "dataType": "double",
            "sourceColumn": "TauxChange_EUR",
            "summarizeBy": "sum"
          },
          {
            "name": "MontantNet_EUR",
            "lineageTag": "90a2f662-5f45-48ba-91cc-9dd5db41c037",
            "dataType": "double",
            "sourceColumn": "MontantNet_EUR",
            "summarizeBy": "sum"
          },
          {
            "name": "Statut",
            "lineageTag": "743db097-dfd0-4732-a4f2-478ff3932346",
            "dataType": "string",
            "sourceColumn": "Statut",
            "summarizeBy": "none"
          },
          {
            "name": "Courtier",
            "lineageTag": "f5a10559-4730-4bc0-9d9e-28d458deabcf",
            "dataType": "string",
            "sourceColumn": "Courtier",
            "summarizeBy": "none"
          },
          {
            "name": "Operateur",
            "lineageTag": "6f38479a-dd21-4a4e-996b-6a9a141c8200",
            "dataType": "string",
            "sourceColumn": "Operateur",
            "summarizeBy": "none"
          },
          {
            "type": "calculated",
            "name": "Revenus EUR",
            "lineageTag": "98e2bb5b-39c1-4784-af07-b63371c6cca7",
            "dataType": "double",
            "expression": "fact_transactions[MontantNet_EUR]",
            "summarizeBy": "none"
          }
        ],
        "measures": [
          {
            "name": "Nb Tx Moy. / Client",
            "expression": "DISTINCTCOUNT(fact_transactions[TransactionID]) / DISTINCTCOUNT(dim_clients[ClientID])",
            "lineageTag": "9955aec2-a231-4f15-b208-2ebc29fda1a7"
          },
          {
            "name": "Revenus Totaux (EUR)",
            "expression": "SUM(fact_transactions[MontantNet_EUR])",
            "lineageTag": "49e1eb32-c49a-494e-9643-6b6b84b0b5c9"
          },
          {
            "name": "Count Distinct TransactionID",
            "expression": "DISTINCTCOUNT(fact_transactions[TransactionID])",
            "lineageTag": "f42413b2-50d7-4bff-8b0c-79e1b521bddf"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:/Users/AlexandreLARRY/Desktop/Migration Qlik PBI/REPORTIMUS-QLIK-TO-POWERBI/examples/edr-demo/input/fact_transactions.csv\"),[Delimiter=\",\", Columns=16, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Types\" = Table.TransformColumnTypes(#\"Promoted Headers\", {{\"DateTransaction\", type datetime}, {\"Quantite\", type number}, {\"PrixUnitaire\", type number}, {\"MontantBrut\", type number}, {\"Frais\", type number}, {\"MontantNet\", type number}, {\"TauxChange_EUR\", type number}, {\"MontantNet_EUR\", type number}}, \"en-US\")",
                "in",
                "    #\"Changed Types\""
              ]
            }
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "dim_portefeuilles_dim_clients_ClientID",
        "fromTable": "dim_portefeuilles",
        "fromColumn": "ClientID",
        "toTable": "dim_clients",
        "toColumn": "ClientID"
      },
      {
        "name": "fact_alertes_risque_dim_clients_ClientID",
        "fromTable": "fact_alertes_risque",
        "fromColumn": "ClientID",
        "toTable": "dim_clients",
        "toColumn": "ClientID",
        "isActive": false
      },
      {
        "name": "fact_cours_historiques_dim_instruments_InstrumentID",
        "fromTable": "fact_cours_historiques",
        "fromColumn": "InstrumentID",
        "toTable": "dim_instruments",
        "toColumn": "InstrumentID"
      },
      {
        "name": "fact_positions_dim_instruments_InstrumentID",
        "fromTable": "fact_positions",
        "fromColumn": "InstrumentID",
        "toTable": "dim_instruments",
        "toColumn": "InstrumentID"
      },
      {
        "name": "fact_transactions_dim_instruments_InstrumentID",
        "fromTable": "fact_transactions",
        "fromColumn": "InstrumentID",
        "toTable": "dim_instruments",
        "toColumn": "InstrumentID"
      },
      {
        "name": "fact_alertes_risque_dim_portefeuilles_PortefeuilleID",
        "fromTable": "fact_alertes_risque",
        "fromColumn": "PortefeuilleID",
        "toTable": "dim_portefeuilles",
        "toColumn": "PortefeuilleID"
      },
      {
        "name": "fact_performances_dim_portefeuilles_PortefeuilleID",
        "fromTable": "fact_performances",
        "fromColumn": "PortefeuilleID",
        "toTable": "dim_portefeuilles",
        "toColumn": "PortefeuilleID"
      },
      {
        "name": "fact_positions_dim_portefeuilles_PortefeuilleID",
        "fromTable": "fact_positions",
        "fromColumn": "PortefeuilleID",
        "toTable": "dim_portefeuilles",
        "toColumn": "PortefeuilleID"
      },
      {
        "name": "fact_transactions_dim_portefeuilles_PortefeuilleID",
        "fromTable": "fact_transactions",
        "fromColumn": "PortefeuilleID",
        "toTable": "dim_portefeuilles",
        "toColumn": "PortefeuilleID"
      },
      {
        "name": "fact_alertes_risque_dim_calendrier_DateAlerte",
        "fromTable": "fact_alertes_risque",
        "fromColumn": "DateAlerte",
        "toTable": "dim_calendrier",
        "toColumn": "Date"
      },
      {
        "name": "fact_cours_historiques_dim_calendrier_Date",
        "fromTable": "fact_cours_historiques",
        "fromColumn": "Date",
        "toTable": "dim_calendrier",
        "toColumn": "Date"
      },
      {
        "name": "fact_performances_dim_calendrier_PeriodeDate",
        "fromTable": "fact_performances",
        "fromColumn": "PeriodeDate",
        "toTable": "dim_calendrier",
        "toColumn": "Date"
      },
      {
        "name": "fact_positions_dim_calendrier_SnapshotDate",
        "fromTable": "fact_positions",
        "fromColumn": "SnapshotDate",
        "toTable": "dim_calendrier",
        "toColumn": "Date"
      },
      {
        "name": "fact_transactions_dim_calendrier_DateTransaction",
        "fromTable": "fact_transactions",
        "fromColumn": "DateTransaction",
        "toTable": "dim_calendrier",
        "toColumn": "Date"
      },
      {
        "name": "dim_clients_dim_conseillers_Conseiller",
        "fromTable": "dim_clients",
        "fromColumn": "Conseiller",
        "toTable": "dim_conseillers",
        "toColumn": "ConseillerID"
      }
    ]
  }
}